"""membuat tabel admin

Revision ID: 6caca7333a61
Revises: b05db22d6acd
Create Date: 2024-11-04 13:30:08.454815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6caca7333a61'
down_revision = 'b05db22d6acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kehadiran')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kehadiran',
    sa.Column('id_kehadiran', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('id_siswa', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('tanggal', sa.DATE(), nullable=False),
    sa.Column('status', mysql.ENUM('Hadir', 'Sakit', 'Alpa'), nullable=False),
    sa.ForeignKeyConstraint(['id_siswa'], ['siswa.id_siswa'], name='kehadiran_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_kehadiran'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
